FROM node:18-alpine as builder


# Pass the environment variables to the build command
ARG PORT
ARG APP_NAME
ARG HOST
ARG FRONTEND_HOST
ARG PG_HOST
ARG PG_PORT
ARG PG_USERNAME
ARG PG_PASSWORD
ARG PG_DATABASE
ARG SUPERTOKENS_TENANT_ID
ARG SUPERTOKENS_API_URL
ARG SUPERTOKENS_API_KEY

# Set the environment variables for the build process
ENV PORT=$PORT
ENV APP_NAME=$APP_NAME
ENV HOST=$HOST
ENV FRONTEND_HOST=$FRONTEND_HOST
ENV PG_HOST=$PG_HOST
ENV PG_PORT=$PG_PORT
ENV PG_USERNAME=$PG_USERNAME
ENV PG_DATABASE=$PG_DATABASE
ENV SUPERTOKENS_TENANT_ID=$SUPERTOKENS_TENANT_ID
ENV SUPERTOKENS_API_URL=$SUPERTOKENS_API_URL
ENV SUPERTOKENS_API_KEY=$SUPERTOKENS_API_KEY

# Set the working directory inside the container
WORKDIR /app

COPY package*.json ./
RUN yarn
COPY . .
RUN yarn build

FROM node:20-alpine as runner

WORKDIR /app

COPY --from=builder /app .

EXPOSE 8080

CMD ["yarn", "start:prod"]